-- ┌──────────────────┐
-- │ Mini.cursorword  │
-- └──────────────────┘
--
-- Autohighlight word under cursor with a customizable delay.
-- Word boundaries are defined based on `:h 'iskeyword'` option.
--
-- It is not enabled by default because its effects are a matter of taste.
-- Uncomment next line (use `gcc`) to enable.

-- MiniDeps.later(function() require('mini.cursorword').setup() end)
